import React,{useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {ArrowUpRight,Radio,Wifi,ArrowRight,ArrowDownToLine,Activity,Users,Ellipsis,FlaskConical,RefreshCw,Check} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Button,Status,Modal,Field,Select,ErrorBox,SectionHead} from './shared';
import {api,errorText,time} from '../lib/api';
export const Metrics=({stats,openTickets}:any)=><div className="metric-grid">{[{title:'Access points online',value:stats.online,suffix:`/ ${stats.total}`,icon:Radio,foot:`${stats.congested} congested · ${stats.offline} offline · ${stats.stale} unknown`,tone:'green'},{title:'Connected clients',value:stats.clients,suffix:'',icon:Users,foot:stats.stale?'Fresh feeds only':'Across all reporting access points',tone:'blue'},{title:'Active alerts',value:stats.congested+stats.offline+stats.stale,suffix:'',icon:Activity,foot:`${stats.offline} critical · ${stats.congested+stats.stale} warnings`,tone:'amber'},{title:'Open tickets',value:openTickets,suffix:'',icon:ClipboardIcon,foot:'Awaiting investigation or resolution',tone:'violet'}].map((m,i)=><div className={`metric-card ${m.tone}`} data-testid={`metric-${i}`} key={m.title}><div className="metric-top"><span>{m.title}</span><m.icon size={17}/></div><div className="metric-value">{m.value}<span>{m.suffix}</span><div className={`spark-bars spark-${i}`}>{[18,26,22,34,25,39,32,43,37,48,44,52].map((h,j)=><i key={j} style={{height:Math.max(8,h-(i*7+j%3*4))}}/>)}</div></div><p><span className="tiny-dot"/>{m.foot}</p></div>)}</div>;
const ClipboardIcon=({size}:any)=><ArrowDownToLine size={size}/>;
export const TrafficChart=({history,title='Network activity',height=235}:any)=>{
 const [period,setPeriod]=useState('24h'); const hours=period==='24h'?24:period==='6h'?6:1;const filtered=history.filter((x:any)=>new Date(x.timestamp).getTime()>Date.now()-hours*3600000);
 return <section className="chart-section"><SectionHead title={title}><div className="segmented">{['1h','6h','24h'].map(p=><button data-testid={`chart-range-${p}`} onClick={()=>setPeriod(p)} className={period===p?'selected':''} key={p}>{p}</button>)}</div></SectionHead><div className="chart-legend"><span><i className="blue-square"/>Connected clients</span><span><i className="green-square"/>Throughput (Mbps)</span><span className="chart-unit">SYNTHETIC TELEMETRY</span></div><div data-testid="network-activity-chart" className="traffic-chart" style={{height}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={filtered} margin={{top:10,right:8,left:-27,bottom:0}}><defs><linearGradient id="clientsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5293ff" stopOpacity={.23}/><stop offset="100%" stopColor="#5293ff" stopOpacity={0}/></linearGradient><linearGradient id="trafficFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3cd4a0" stopOpacity={.08}/><stop offset="100%" stopColor="#3cd4a0" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--line)" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="timestamp" tickFormatter={x=>time(x)} minTickGap={65} tick={{fill:'var(--muted)',fontSize:10}} axisLine={false} tickLine={false} dy={7}/><YAxis tick={{fill:'var(--muted)',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--line)',borderRadius:5,fontSize:12}} labelFormatter={x=>time(String(x),true)}/><Area type="monotone" name="Clients" dataKey="clients" stroke="#5293ff" strokeWidth={2} fill="url(#clientsFill)" animationDuration={700}/><Area type="monotone" name="Mbps" dataKey="throughput" stroke="#3cd4a0" strokeWidth={1.6} fill="url(#trafficFill)" animationDuration={700}/></AreaChart></ResponsiveContainer></div></section>;
};
export const APTable=({aps,onSelect,limit}:any)=><div className="table-wrap"><table className="data-table ap-table"><thead><tr><th>ACCESS POINT</th><th>STATUS</th><th>CLIENTS</th><th>UTILIZATION</th><th>LAST SEEN</th><th/></tr></thead><tbody>{aps.slice(0,limit||aps.length).map((a:any)=><tr key={a.id} data-testid={`ap-row-${a.id}`} onClick={()=>onSelect?.(a)} className={onSelect?'clickable':''}><td><div className="asset-name"><span className={`asset-icon ${a.status}`}><Wifi size={16}/></span><div><strong>{a.tag}</strong><small>{a.lab_name}</small></div></div></td><td><Status value={a.status} id={`ap-status-${a.id}`}/></td><td className="mono">{a.clients??'—'}</td><td><div className="utilization"><span className={`utilization-bar ${a.status}`}><i style={{width:`${a.load||0}%`}}/></span><span className="mono">{a.load==null?'—':`${a.load}%`}</span></div></td><td className="mono muted">{time(a.last_seen)} <span className="faint">PHT</span></td><td>{onSelect&&<button aria-label={`Inspect ${a.tag}`} title="Inspect access point" className="icon-button" data-testid={`inspect-${a.id}`} onClick={e=>{e.stopPropagation();onSelect(a);}}><ArrowUpRight size={15}/></button>}</td></tr>)}</tbody></table>{!aps.length&&<div className="empty" data-testid="no-access-points">No access points match this view.</div>}</div>;
export const Simulation=({open,onClose,aps,onDone}:any)=>{
 const [asset,setAsset]=useState('all'),[scenario,setScenario]=useState('congestion'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const apply=async()=>{setBusy(true);setError('');setSuccess('');try{const r=await api.post('/simulation',{asset_id:asset,scenario});setSuccess(r.data.message);onDone();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 return <Modal open={open} onClose={onClose} title="Simulation control room" description="Synthetic telemetry only · no live network changes" id="simulation-dialog"><Field label="Target access point" id="scenario-asset"><Select id="scenario-asset" value={asset} onChange={(e:any)=>setAsset(e.target.value)}><option value="all">All access points</option>{aps.map((a:any)=><option key={a.id} value={a.id}>{a.tag} · {a.lab_name}</option>)}</Select></Field><div className="scenario-options">{[['congestion','Congestion','High utilization and client load'],['outage','AP outage','Explicit access point failure'],['feed','Feed interruption','Stale / unknown, never an inferred outage'],['normal','Recovery','Restore normal synthetic telemetry']].map(([key,title,sub])=><button key={key} className={scenario===key?'selected':''} data-testid={`scenario-${key}`} onClick={()=>{setScenario(key);setSuccess('');}}><span className={`scenario-dot ${key}`}/><span><strong>{title}</strong><small>{sub}</small></span>{scenario===key&&<Check size={16}/>}</button>)}</div><ErrorBox error={error}/>{success&&<div className="success-box" data-testid="simulation-success"><Check size={17}/>{success}</div>}<Button variant="primary" id="apply-scenario" disabled={busy} onClick={apply}><FlaskConical size={16}/>{busy?'Applying scenario…':'Run simulation'}</Button></Modal>;
};