import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Download,Search,RefreshCw,TriangleAlert,ArrowUpRight,CheckCheck,FlaskConical} from 'lucide-react';
import {PageTitle,Button,Status,Select,ErrorBox,Loading,Empty,SectionHead,useData} from '../components/shared';
import {time} from '../lib/api';
function downloadCSV(name:string,rows:any[][]){
 const escape=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';
 const blob=new Blob(['\ufeff'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);
}
export function Reports(){
 const {data,error,busy,load}=useData('/reports');const exportReport=()=>{if(data)downloadCSV('atlas-operational-report.csv',[['Atlas NetCare academic demo','Generated at',data.generated_at],['Metric','Value'],['Total tickets',data.tickets_total],['Open',data.open],['In progress',data.in_progress],['Resolved',data.resolved],['Inspections',data.checklists_total],['Passed',data.passed],['Failed',data.failed],['Missed acknowledgements',data.missed_acknowledgements],['Mean resolution minutes',data.mean_resolution_minutes??'No resolutions'],[],['Lab','Active assets','Inspections','Open tickets'],...data.labs.map((l:any)=>[l.name,l.assets,l.inspections,l.open_tickets])]);};
 return <><PageTitle title="Operational reports" subtitle="Persisted operations, measured outcomes."><Button id="refresh-reports" onClick={load}><RefreshCw size={15}/>Refresh</Button><Button id="export-report" variant="primary" disabled={!data} onClick={exportReport}><Download size={15}/>Export CSV</Button></PageTitle><ErrorBox error={error} retry={load}/>{busy&&!data?<Loading/>:data&&<><div className="monitor-status-strip"><span className="feed-label"><FlaskConical size={13}/> ACADEMIC DEMO</span><span data-testid="report-generated">Generated {time(data.generated_at,true)} PHT</span><span>All-time operational records</span></div><div className="report-grid">{[['Inspections submitted',data.checklists_total,`${data.passed} passed · ${data.failed} with faults`],['Tickets resolved',data.resolved,`${data.tickets_total} tickets reported`],['Mean resolution time',data.mean_resolution_minutes==null?'—':`${data.mean_resolution_minutes}m`,'From report to saved resolution'],['Missed acknowledgements',data.missed_acknowledgements,`${data.acknowledged_shifts} shifts acknowledged`]].map(([title,value,sub],i)=><div className="report-stat" data-testid={`report-stat-${i}`} key={title}><span>{title}</span><strong>{value}</strong><small>{sub}</small></div>)}</div><div className="report-two"><section><SectionHead title="Ticket outcomes"/><div className="distribution" data-testid="ticket-outcomes-chart">{[data.open,data.in_progress,data.resolved].map((v:number,i:number)=><i key={i} style={{flex:v}}/>)}</div><div className="distribution-legend"><span>Open · {data.open}</span><span>In progress · {data.in_progress}</span><span>Resolved · {data.resolved}</span></div></section><section><SectionHead title="Inspection outcomes"/>{data.checklists_total?<><div className="distribution" data-testid="inspection-outcomes-chart"><i style={{flex:data.passed,background:'var(--green)'}}/><i style={{flex:data.failed}}/></div><div className="distribution-legend"><span>Passed · {data.passed}</span><span>With faults · {data.failed}</span></div></>:<p className="muted small" data-testid="reports-no-inspections">No inspections submitted yet.</p>}</section></div><SectionHead title="Lab operations"/><div className="table-wrap"><table className="data-table"><thead><tr><th>LAB</th><th>ACTIVE ASSETS</th><th>INSPECTIONS</th><th>OPEN TICKETS</th></tr></thead><tbody>{data.labs.map((l:any,i:number)=><tr key={l.name} data-testid={`report-lab-${i}`}><td>{l.name}</td><td className="mono">{l.assets}</td><td className="mono">{l.inspections}</td><td className="mono">{l.open_tickets}</td></tr>)}</tbody></table></div><p className="permission-notice" data-testid="report-scope">Resolution times describe this demo’s operational records, not production network availability.</p></>}</>;
}

export function Audit(){
 const {data,error,busy,load}=useData('/audit'),[search,setSearch]=useState('');const rows=data?.filter((a:any)=>(a.action+' '+a.actor+' '+a.detail).toLowerCase().includes(search.toLowerCase()));
 return <><PageTitle title="Audit trail" subtitle="A traceable history of campus operations and privileged changes."><Button id="refresh-audit" onClick={load}><RefreshCw size={15}/>Refresh</Button><Button id="export-audit" onClick={()=>downloadCSV('atlas-audit.csv',[['Timestamp UTC','Actor','Action','Detail'],...(rows||[]).map((a:any)=>[a.timestamp,a.actor,a.action,a.detail])])} disabled={!data}><Download size={15}/>Export CSV</Button></PageTitle><ErrorBox error={error} retry={load}/><div className="page-search"><div className="search-field"><Search size={15}/><input data-testid="audit-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search actor, action, or asset…"/></div><span className="count-label" data-testid="audit-count">{rows?.length||0} events · latest 1,000</span></div>{busy&&!data?<Loading/>:rows?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>TIMESTAMP (PHT)</th><th>ACTOR</th><th>ACTION</th><th>DETAILS</th></tr></thead><tbody>{rows.map((a:any)=><tr key={a.id} data-testid={`audit-event-${a.id}`}><td className="mono small">{time(a.timestamp,true)}</td><td>{a.actor}</td><td className="audit-action">{a.action}</td><td className="audit-detail muted">{a.detail}</td></tr>)}</tbody></table></div>:<Empty text="No audit events match this view."/>}</>;
}

export function Alerts(){
 const {data,error,busy,load}=useData('/alerts'),[filter,setFilter]=useState('active');const rows=data?.filter((a:any)=>filter==='all'||(filter==='active'?a.active:!a.active));
 return <><PageTitle title="Alert center" subtitle="Synthetic network anomalies and their recovery history."><Button id="refresh-alerts" onClick={load}><RefreshCw size={15}/>Refresh</Button></PageTitle><ErrorBox error={error} retry={load}/><div className="simulation-strip"><div><FlaskConical size={16}/><strong>Simulated notifications</strong><span>In-app only. No email or closed-browser alarms.</span></div><Link to="/shifts" data-testid="alerts-shift-link" className="inline-link">Shift reminders <ArrowUpRight size={12}/></Link></div><div className="filter-tabs">{[['active','Active alerts'],['recovered','Recovered'],['all','All history']].map(([key,label])=><button key={key} data-testid={`alerts-filter-${key}`} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}<span>{data?.filter((a:any)=>key==='all'||(key==='active'?a.active:!a.active)).length||0}</span></button>)}</div>{busy&&!data?<Loading/>:rows?.length?<div className="alert-grid">{rows.map((a:any)=><article key={a.id} className={`alert-card ${a.status}`} data-testid={`alert-${a.id}`}>{a.active?<TriangleAlert className="alert-icon" size={21}/>:<CheckCheck className="alert-icon" size={21}/>}<div><div className="alert-meta"><strong>{a.asset_tag}</strong><span className="demo-badge">SIMULATED</span></div><h2>{a.title}</h2><p>{a.detail}</p><small>{a.lab_name} · {time(a.created_at,true)} PHT{a.resolved_at?` · Recovered ${time(a.resolved_at,true)} PHT`:''}</small></div><Status value={a.active?a.status:'resolved'} id={`alert-status-${a.id}`}/><Link className="icon-button" title="Inspect access point" aria-label="Inspect access point" to={`/monitoring?ap=${a.asset_id}`} data-testid={`alert-inspect-${a.id}`}><ArrowUpRight size={17}/></Link></article>)}</div>:<Empty text="No alerts in this view."/>}</>;
}